### PR TITLE
Fix JSON stringify circular structure when logging

### LINKED ISSUE #606: `TypeError: Converting circular structure to JSON` when downloading Coder binary
We're seeing this exception when the extension tries to download a new version of the Coder CLI in Cursor.

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property 'parser' -> object with constructor 'HTTPParser'
```

It seems like this only affects older versions of VSCode, as I can't reproduce this in VSCode 1.104.2. The bug was introduced in extension version 1.11.0. The download works when downgrading the extension to version 1.10.1.

The output logs preceding this:

```
2025-10-02 14:14:18.402 [info] Downloading since existing binary does not match the server version
2025-10-02 14:14:18.403 [info] Removed coder-darwin-arm64.temp-bs1fi
2025-10-02 14:14:18.403 [info] Downloading binary from /bin/coder-darwin-arm64
2025-10-02 14:14:18.437 [info] Using ETag 93ba9ec75313948cc85baadc9914917c70e4350e
2025-10-02 14:14:18.862 [warning] Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
```

The call stack looks like this, when I run in debug mode:

<details><summary>Full stack trace</summary>

```
formatContentLength (/Users/davidv/work/vscode-coder/src/logging/formatters.ts:40)
logResponse (/Users/davidv/work/vscode-coder/src/logging/httpLogger.ts:68)
<anonymous> (/Users/davidv/work/vscode-coder/src/api/coderApi.ts:232)
process.processTicksAndRejections (internal/process/task_queues:95)
Promise.then (Unknown Source:0)
_request (/Users/davidv/work/vscode-coder/node_modules/axios/dist/node/axios.cjs:4599)
request (/Users/davidv/work/vscode-coder/node_modules/axios/dist/node/axios.cjs:4478)
Axios.<computed> (/Users/davidv/work/vscode-coder/node_modules/axios/dist/node/axios.cjs:4647)
wrap (/Users/davidv/work/vscode-coder/node_modules/axios/dist/node/axios.cjs:31)
download (/Users/davidv/work/vscode-coder/src/core/cliManager.ts:253)
fetchBinary (/Users/davidv/work/vscode-coder/src/core/cliManager.ts:133)
await (Unknown Source:0)
processTicksAndRejections (internal/process/task_queues:95)
await (Unknown Source:0)
processTicksAndRejections (internal/process/task_queues:95)
await (Unknown Source:0)
processTicksAndRejections (internal/process/task_queues:95)
await (Unknown Source:0)
setup (/Users/davidv/work/vscode-coder/src/remote/remote.ts:301)
await (Unknown Source:0)
```

</details>

https://github.com/coder/vscode-coder/blob/67e85e6106000d6729f20cac5d35b3db1e58df9c/src/logging/formatters.ts#L40
https://github.com/coder/vscode-coder/blob/67e85e6106000d6729f20cac5d35b3db1e58df9c/src/logging/httpLogger.ts#L68
https://github.com/coder/vscode-coder/blob/67e85e6106000d6729f20cac5d35b3db1e58df9c/src/api/coderApi.ts#L232
https://github.com/coder/vscode-coder/blob/67e85e6106000d6729f20cac5d35b3db1e58df9c/src/core/cliManager.ts#L253
https://github.com/coder/vscode-coder/blob/67e85e6106000d6729f20cac5d35b3db1e58df9c/src/core/cliManager.ts#L133

#### IDE version information

Cursor Version: 1.7.28 (Universal)
VSCode Version: 1.99.3
Commit: adb0f9e3e4f184bba7f3fa6dbfd72ad0ebb8cfd0
Date: 2025-10-01T02:45:21.769Z
Electron: 34.5.8
Chromium: 132.0.6834.210
Node.js: 20.19.1
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.6.0

### PR DESCRIPTION
**Pull request by EhabY**
Closes #606

### CODE REVIEW

File: src/logging/formatters.ts [hunk 1]
```diff
@@ -66,8 +85,38 @@ export function formatHeaders(headers: Record<string, unknown>): string {
...
+				return "[Symbol]";
+			}
+			if (typeof value === "bigint") {
+				return value.toString();
+			}
+
+			return value;
+		});
+	} catch {
+		return null;
```
Comment (ibetitsmike) [inline src/logging/formatters.ts]: No error handling?

Comment (EhabY) [reply src/logging/formatters.ts]: I am not sure if we want error handling here since this is purely for estimating the `data`/`body` size and printing the body. Should it log the error here on `warn`/`error`?

Comment (ibetitsmike) [reply src/logging/formatters.ts]: if the path is non-critical, ie. no estimated size doesn't result in unexpected behavior on the client - I'm ok with no logs; 

but if the consequence is that something breaks down the road - a warn would be nice for troubleshooting

Comment (EhabY) [reply src/logging/formatters.ts]: The two calls to `safeStringify` are for logging (estimating body size and printing the actual body if the log level is sufficient) so def non-critical. Could still be useful to log since I do not think it's normal that we pass a recursive object here (`response.data`/`request.data` should both be simple JSON objects or primitives)

File: src/logging/formatters.ts [hunk 2]
```diff
@@ -66,8 +85,38 @@ export function formatHeaders(headers: Record<string, unknown>): string {
...
 }
+
+function safeStringify(data: unknown): string | null {
+	try {
+		const seen = new WeakSet();
+		return JSON.stringify(data, (_key, value) => {
+			// Handle circular references
+			if (typeof value === "object" && value !== null) {
+				if (seen.has(value)) {
+					return "[Circular]";
```
Comment (code-asher) [inline src/logging/formatters.ts]: Oh woah `JSON.stringify` does not handle circular references??  Huh yeah

```
> t = {}
> t.t = t
> JSON.stringify(t)
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 't' closes the circle
    at JSON.stringify (<anonymous>)
```

I wonder if we should use `util.inspect`?

```
> t.foo = "bar"
> t.fn = () => undefined
> t.sy = Symbol("foo")
> t.b = BigInt("0x1fffffffffffff")
> util.inspect(t, { breakLength: Infinity })
"<ref *1> { t: [Circular *1], foo: 'bar', fn: [Function (anonymous)], sy: Symbol(foo), b: 9007199254740991n }"

Comment (EhabY) [reply src/logging/formatters.ts]: Oooh I kind of like `util.inspect` since it can handle node objects well and doesn't break easily. Since we want to print the whole body (or estimate based on that), I can configure it as such:

```ts
try {
	return util.inspect(data, {
		showHidden: false,
		depth: Infinity,
		maxArrayLength: Infinity,
		maxStringLength: Infinity,
		breakLength: Infinity,
		compact: true,
		getters: false, // avoid side-effects
	});
} catch {
	// Should rarely happen but just in case
	return null;
}
```

Let me write some tests and see how it looks.

My only concern here is performance, if we get big objects and we have to estimate the size often then it might be slow... At least with the `body` log level we have to enable it to print it, here we always estimate

File: src/logging/formatters.ts [hunk 3]
```diff
@@ -18,7 +21,7 @@ export function formatTime(ms: number): string {
 }
 
 export function formatMethod(method: string | undefined): string {
-	return (method ?? "GET").toUpperCase();
+	return (method ? method : "GET").toUpperCase();
```
Comment (code-asher) [inline src/logging/formatters.ts]: Could be `method || "GET"`

File: src/logging/formatters.ts [hunk 4]
```diff
@@ -66,8 +75,25 @@ export function formatHeaders(headers: Record<string, unknown>): string {
...
+			showHidden: false,
+			depth: Infinity,
+			maxArrayLength: Infinity,
+			maxStringLength: Infinity,
+			breakLength: Infinity,
+			compact: true,
+			getters: false, // avoid side-effects
+		});
+	} catch {
+		// Should rarely happen but just in case
```
Comment (code-asher) [inline src/logging/formatters.ts]: Is this just to be defensive or are there known ways `util.inspect` can throw?

**Review by code-asher — APPROVED** [review]
Very nice!

File: src/logging/formatters.ts (hunk 2 above)
Comment (code-asher) [reply src/logging/formatters.ts]: True, maybe we could get the size in another way, like iterate through the object and tally up the individual key and value sizes.  That would also fix how `undefined` would be printed as a string and take up bytes even though it really takes up zero bytes (I assume).  Actually I guess that would depend on whether the response literally returned `undefined` in the response or not.  Is there a way to get the raw unparsed response size maybe?  Should be a byte stream or array somewhere I would imagine, but not sure we have access to it.

File: src/logging/utils.ts [hunk 5]
```diff
@@ -5,17 +5,25 @@ export function shortId(id: string): string {
...
+ * otherwise returns undefined (e.g., for plain objects and arrays that would require serialization).
+ */
 export function sizeOf(data: unknown): number | undefined {
 	if (data === null || data === undefined) {
 		return 0;
 	}
-	if (typeof data === "string") {
-		return Buffer.byteLength(data);
+	if (typeof data === "number" || typeof data === "boolean") {
+		return 8;
```
Comment (code-asher) [inline src/logging/utils.ts:25]: Ah wait actually is a boolean eight bytes in v8?  I thought maybe it was 4 bytes

File: src/logging/formatters.ts (hunk 4 above)
Comment (EhabY) [reply src/logging/formatters.ts]: Apparently it could still throw sometimes like if a getter throws, getters are not traversed here so it's more defensive I suppose

File: src/logging/utils.ts (hunk 5 above)
Comment (EhabY) [reply src/logging/utils.ts:25]: Both are kinda estimations and depend on the system but yes 4 is more accurate than 8. Changed

File: src/logging/formatters.ts (hunk 3 above)
Comment (EhabY) [reply src/logging/formatters.ts]: Right, I keep confusing `??` (for undefined only) with `||` (all falsey  values)

Comment (code-asher) [reply src/logging/formatters.ts]: Undefined and null as well, I think!

File: src/logging/formatters.ts (hunk 2 above)
Comment (EhabY) [reply src/logging/formatters.ts]: I tried to use https://www.npmjs.com/package/object-sizeof but it just returns an error in case of recursive objects.

> Node.js version uses the Buffer.from(objectToString) method to convert the object's string representation to a buffer, and then it uses the byteLength property to obtain the buffer size in bytes.

So this is very similar anyway.

> Is there a way to get the raw unparsed response size maybe?

I think this is the way, unparsed responses are always `string` and thus much simpler to get exact sizes, same for the request before sending it to the server. I've added axios request and response transformers that just read the raw response/request body and gets the size from that and seems to work well!

File: src/api/coderApi.ts [hunk 6]
```diff
@@ -228,6 +251,66 @@ function addLoggingInterceptors(client: AxiosInstance, logger: Logger) {
...
+	}
+
+	const size = sizeOf(data);
+	if (size !== undefined) {
+		return size;
+	}
+
+	// Fallback
+	const stringified = serializeValue(data);
+	return stringified === null ? undefined : Buffer.byteLength(stringified);
```
Comment (EhabY) [inline src/api/coderApi.ts]: I think this is not needed and is not even executed while I was testing. Could be there just in case 🤔

File: src/logging/formatters.ts (hunk 2 above)
Comment (code-asher) [reply src/logging/formatters.ts]: Oh woah that is amazing!!  Nice work figuring that out :tada:

File: src/api/coderApi.ts [hunk 7]
```diff
@@ -228,6 +251,66 @@ function addLoggingInterceptors(client: AxiosInstance, logger: Logger) {
...
+	config: RequestConfigWithMeta,
+): AxiosResponseTransformer[] {
+	return [
+		(data: unknown, headers: AxiosHeaders) => {
+			const transformerArray = Array.isArray(transformer)
+				? transformer
+				: [transformer];
+
+			// Transform the request first then estimate the size
+			const result = transformerArray.reduce(
```
Comment (code-asher) [inline src/api/coderApi.ts:265]: Do we need to manually call the other transformer(s)?  Since these already take an array I assume they call them in sequence so we could do something like:

```typescript
config.transformRequest = [
  (data, headers) => {
    config.rawRequestSIze = getSize(headers, data);
    return data;
  },
  ...(config.transformRequest || client.defaults.transformResponse || []),
]
```

That way ours gets called first with the original data, we record the size, then it goes on through the regular transform chain.

File: src/api/coderApi.ts [hunk 8]
```diff
@@ -228,6 +251,66 @@ function addLoggingInterceptors(client: AxiosInstance, logger: Logger) {
...
+	];
+}
+
+function getSize(headers: AxiosHeaders, data: unknown): number | undefined {
+	const contentLength = headers["content-length"];
+	if (contentLength !== undefined) {
+		return parseInt(contentLength, 10);
+	}
+
+	const size = sizeOf(data);
```
Comment (code-asher) [inline src/api/coderApi.ts]: You mentioned the raw data is a string right?  Could we just do something like:

```typescript
// This must be called before any other transforms to ensure we operate on the original string.
return typeof data === "string" ? Buffer.byteLength(data) : undefined;
```

That way, no need to maintain `sizeOf`

File: src/logging/utils.ts [hunk 9]
```diff
@@ -36,6 +44,19 @@ export function sizeOf(data: unknown): number | undefined {
 	return undefined;
 }
 
-export function createRequestId(): string {
-	return crypto.randomUUID().replace(/-/g, "");
+export function serializeValue(data: unknown): string | null {
```
Comment (code-asher) [inline src/logging/utils.ts]: I liked the `stringify` name better personally, to me serialize sounds like this should convert to some format like yaml or protobuf or whatever, while this is just the original format but in printable string form.

File: src/api/coderApi.ts (hunk 7 above)
Comment (EhabY) [reply src/api/coderApi.ts:265]: For requests we have to call ours last because we want to measure what's sent over the wire, also the transformers here could be doing the serializing anyway. It's the opposite for the response, where we have to get the size first thing since that is also what's sent over the wire

File: src/api/coderApi.ts (hunk 8 above)
Comment (EhabY) [reply src/api/coderApi.ts]: Apparently it could be other types, for example, for binary data it could be `ArrayBuffer`. `sizeOf` is also used to get the size of websocket data as well. I prefer keeping it since it just handles the primitives, buffers, and objects with `size` property (very fast and simple)

File: src/logging/utils.ts (hunk 9 above)
Comment (EhabY) [reply src/logging/utils.ts]: Changed back to `safeStringify`

File: src/api/coderApi.ts (hunk 8 above)
Comment (EhabY) [reply src/api/coderApi.ts]: I removed the stringification so it's something like this:

```ts
function getSize(headers: AxiosHeaders, data: unknown): number | undefined {
	const contentLength = headers["content-length"];
	if (contentLength !== undefined) {
		return parseInt(contentLength, 10);
	}

	return sizeOf(data);
}
```

Where `sizeOf` handles primitive sizes, buffers, and objects with `size`

File: src/api/coderApi.ts (hunk 6 above)
Comment (EhabY) [reply src/api/coderApi.ts]: Removed this for now

File: src/api/coderApi.ts (hunk 7 above)
Comment (code-asher) [reply src/api/coderApi.ts:265]: Ohhhh right good point we would want the reverse for requests.  We can still avoid calling the transformers ourself right?  Not a huge deal either way, just slightly more idiomatic.

File: src/api/coderApi.ts (hunk 8 above)
Comment (code-asher) [reply src/api/coderApi.ts]: Makes sense to me!  I like that.
