### PR TITLE
Use truncated version with signature fallback

### LINKED ISSUE #573: Adjust the fallback path
We need to adjust the fallback path so that only `MAJOR.MINOR.PATCH` version is included:
https://github.com/coder/vscode-coder/blob/c26018f96e12f7e7bb3c210fd83aef937307e851/src/storage.ts#L235

Signature downloads from [releases.coder.com](https://releases.coder.com/) fail due to a mismatch between the value returned by the [buildinfo](https://coder.com/docs/reference/api/schemas#codersdkbuildinforesponse) endpoint and the object names in the underlying GCS bucket.

Image

### Example:

Currently the handler would attempt to fetch the signature from:
https://releases.coder.com/coder-cli/2.24.1+f97bd76/{detached_signature} 🔴 

Should be:
https://releases.coder.com/coder-cli/2.24.1/{detached_signature} 🟢

### PR DESCRIPTION
**Pull request by code-asher**
Fixes #573

### CODE REVIEW

File: src/storage.ts [hunk 1]
```diff
@@ -139,6 +140,10 @@ export class Storage {
 		// and to log for debugging.
 		const buildInfo = await restClient.getBuildInfo();
 		this.output.info("Got server version", buildInfo.version);
+		const parsedVersion = semver.parse(buildInfo.version);
```
Comment (jdomeracki-coder) [inline src/storage.ts:143]: Do I get it right that it will handle the leading `v`?
https://github.com/npm/node-semver?tab=readme-ov-file#versions

Comment (jdomeracki-coder) [reply src/storage.ts:143]: Nvm, I get it ✔️

Comment (code-asher) [reply src/storage.ts:143]: Yup exactly, I tested with `v2.25.1-devel+92d505c52` (from dev.coder.com).

**Review by jdomeracki-coder — APPROVED** [review]
