### PR TITLE
fix: keep binary in same place, update if needed

### LINKED ISSUE #23: Windows Firewall prompt on every new binary
Every time there's a new version on the server (which is multiple times per day in dev.coder.com) the extension will download a new binary and Windows firewall will prompt to allow network access.

We should figure out a way to prevent the windows firewall thing from popping up (we only need to access over localhost anyways).

### PR DESCRIPTION
**Pull request by jsjoeio**
## Description

@deansheather filed a bug related to the Windows Firewall prompt coming up with every new binary (i.e. every time we download `coder` to an updated version).

After some initial testing, it appears keeping the binary in the same place will make the prompt only appear on the first time.

Previous implementation kept the version in the path.

We decided to refactor things to add support for [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) on the server and then use those changes on the client (aka in the extension).

This means now the client will tell the server "Here's the version I have. What should I do?" and send the appropriate headers.

### Checklist
- [x] if needed, change path/name of location to not include version
- [x] if the binary exists, SHA1 it and use it as the `If-None-Match` header in your request
- [x] Server Response changes
  - [x] on 200 OK: move the binary on top of the old one
  - [x] on 304 Not Modified: delete the temp file and use the old binary

### Testing Plan

TBD

Fixes #23

### CODE REVIEW

File: src/storage.ts [hunk 1]
```diff
@@ -80,32 +81,8 @@ export class Storage {
...
-          this.output.appendLine("The cached binary cannot be executed: " + ex)
-          resolve(false)
-        }
-      })
-      if (valid) {
-        return binPath
-      }
-    }
+    const binPath = this.binaryPath()
+    const exists = await this.checkBinaryExists(binPath)
```
Comment (jsjoeio) [inline src/storage.ts:86]: Most of this is simply refactoring to make the code easier to follow

File: src/storage.ts [hunk 2]
```diff
@@ -114,6 +91,23 @@ export class Storage {
...
+      } else {
+        // Even if the file exists, it could be corrupted.
+        // We run `coder version` to ensure the binary can be executed.
+        this.output.appendLine(`Using existing binary: ${binPath}`)
+        const valid = await this.checkBinaryValid(binPath)
+        if (valid) {
+          return binPath
+        }
+      }
+    }
```
Comment (jsjoeio) [inline src/storage.ts]: This is the meat of the changes

File: src/storage.ts [hunk 3]
```diff
@@ -236,6 +230,10 @@ export class Storage {
     return path.join(this.globalStorageUri.fsPath, "url")
   }
 
+  public getBinaryETag(): string {
+    return crypto.createHash("sha1").update(this.binaryPath()).digest("hex")
+  }
```
Comment (jsjoeio) [inline src/storage.ts]: I believe this is the same `sha1` hashing the backend is using. Although I'd love input on easiest way to check (less familiar on the Go side).

File: src/storage.ts [hunk 4]
```diff
@@ -260,16 +258,57 @@ export class Storage {
     }
   }
 
-  private binaryPath(version: string): string {
+  private binaryPath(): string {
     const os = goos()
     const arch = goarch()
-    let binPath = path.join(this.getBinaryCachePath(), `coder-${os}-${arch}-${version}`)
+    let binPath = path.join(this.getBinaryCachePath(), `coder-${os}-${arch}`)
```
Comment (jsjoeio) [inline src/storage.ts:328]: 🔨  We no longer use the version in the binaryPath. This should fix the Windows prompt issue.

File: src/storage.ts [hunk 5]
```diff
@@ -260,16 +258,57 @@ export class Storage {
...
+
+    switch (resp.status) {
+      case 200:
+        return true
+      case 304:
+      default:
+        return false
+    }
+  }
+
```
Comment (jsjoeio) [inline src/storage.ts]: New logic added based off: https://github.com/coder/coder/pull/5750

**Comment by jsjoeio** [comment]
What's the easiest way to test these changes locally @kylecarbs ?

File: src/storage.ts (hunk 3 above)
Comment (deansheather) [reply src/storage.ts]: SHA1 is universal, so as long as it's a SHA1 hash with hex encoding (lowercase) then it's good.

File: src/storage.ts (hunk 2 above)
Comment (deansheather) [inline src/storage.ts]: I think this logic should be more like:
```
if (exists) {
  const valid = checkBinValid();
  if (valid) {
    return binPath;
  }
  deleteBin();
}

downloadBinary()
```

and the request to the bin endpoint should only be made once. The axios request should be piped to a temp file in the same dir, then once the request is finished:
- if 200: move the temp file on top of the binPath
- if 304: delete the temp file and use the old binPath

Comment (deansheather) [reply src/storage.ts]: Using two requests for this is not necessary

**Review by deansheather — APPROVED** [review]

**Review by deansheather — DISMISSED** [review]
oops meant to request changes

File: src/storage.ts (hunk 2 above)
Comment (jsjoeio) [reply src/storage.ts]: But doesn't that mean we're always downloading a new binary even if we don't have to?

Comment (jsjoeio) [reply src/storage.ts]: Also if the logic is like that, then we'd never get to the `downloadBinary()` right?

Comment (jsjoeio) [reply src/storage.ts]: I'll see if I can clean up to make it only one request.

Comment (deansheather) [reply src/storage.ts]: oh you're right, I meant this:
```
if (exists) {
  const valid = checkBinValid();
  if (!valid) {
    deleteBin();
  }
}

let tempFile = binPath + ".temp-" + randString(8);
let res = await request(serverBinPath, streamToFile: tempFile);

if (res.status == 200) {
  move(tempFile, binPath);
  return binPath;
}
remove(tempFile);
if (res.status != 304) {
  throw new Error("failed to make request to server");
}
return binPath;
```

Comment (jsjoeio) [reply src/storage.ts]: OH, okay that makes more sense. Thank you!

File: src/storage.ts [hunk 6]
```diff
@@ -140,15 +129,12 @@ export class Storage {
         })
       return
     }
-    if (resp.status !== 200) {
```
Comment (deansheather) [inline src/storage.ts:147]: Could avoid piping to the temp file here by checking resp.status == 304 and returning the existing binary path.

Comment (deansheather) [reply src/storage.ts:147]: And also error if the status isn't 200 or 304 here so you don't have to pipe to the file first. I didn't think you could do that but you can judging by the similar check for 404 above.

**Review by deansheather — COMMENTED** [review]
the logic seems OK but I haven't tested it

File: src/storage.ts (hunk 6 above)
Comment (jsjoeio) [reply src/storage.ts:147]: Good idea. I'll refactor.

**Comment by jsjoeio** [comment]
@deansheather re: testing

Let me make these changes, build to a `vsix` then send to you via Slack to test

**Comment by jsjoeio** [comment]
I tested locally on macOS and something is off 

image

Seems like it's trying to use the binary before it's done renaming it?

**Comment by jsjoeio** [comment]
I'm going to try rebasing on `main` and then rebuilding and testing again.

**Comment by jsjoeio** [comment]
I figured it out - I was trying to `rm` the file after `mv`ing and so it was failing because it couldn't remove a file that doesn't exist 🤦🏼‍♂️

**Comment by jsjoeio** [comment]
Tested locally and seems to work 👍🏼 

image

**Comment by jsjoeio** [comment]
@deansheather ready for a new review!

File: src/storage.ts [hunk 7]
```diff
@@ -114,106 +92,152 @@ export class Storage {
...
+    this.output.appendLine(`Using binPath: ${binPath}`)
+    this.output.appendLine(`Using ETag: ${etag}`)
+
     const resp = await axios.get("/bin/" + binName, {
       signal: controller.signal,
       baseURL: baseURL,
       responseType: "stream",
       headers: {
         "Accept-Encoding": "gzip",
+        "If-None-Match": `"${await this.getBinaryETag()}"`,
```
Comment (deansheather) [inline src/storage.ts]:
```suggestion
        "If-None-Match": `"${etag}"`,
```

File: src/storage.ts [hunk 8]
```diff
@@ -114,106 +92,152 @@ export class Storage {
...
+      if (!valid) {
+        const removed = await this.rmBinary(binPath)
+        if (!removed) {
+          vscode.window.showErrorMessage("Failed to remove existing binary!")
+          return undefined
+        }
+      }
+    }
+    const etag = await this.getBinaryETag()
+    this.output.appendLine(`Using binPath: ${binPath}`)
```
Comment (deansheather) [inline src/storage.ts:109]:
```suggestion
    this.output.appendLine(`Using binName: ${binName}`)
    this.output.appendLine(`Using binPath: ${binPath}`)
```

**Review by deansheather — APPROVED** [review]
Looks good and works on Windows for me. The logic seems OK but I'm not a big typescript guy so someone else should approve too

File: package.json [hunk 9]
```diff
@@ -85,6 +85,7 @@
     "build": "webpack",
     "watch": "webpack --watch",
     "package": "webpack --mode production --devtool hidden-source-map",
+    "package:prerelease": "npx vsce package --pre-release",
```
Comment (Kira-Pilot) [inline package.json:88]: This script looks like it publishes a pre-release version of a package. Could you help me understand the general workflow here and how it relates to this issue?

File: src/storage.ts [hunk 10]
```diff
@@ -73,39 +74,16 @@ export class Storage {
...
-          this.output.appendLine("The cached binary cannot be executed: " + ex)
-          resolve(false)
-        }
-      })
-      if (valid) {
-        return binPath
-      }
-    }
+    const binPath = this.binaryPath()
+    const exists = await this.checkBinaryExists(binPath)
```
Comment (Kira-Pilot) [inline src/storage.ts:86]: Do we need to worry about error handling here?

**Review by Kira-Pilot — APPROVED** [review]
Really appreciate the comments you left!

File: package.json (hunk 9 above)
Comment (jsjoeio) [reply package.json:88]: This will build the project and output a `.vsix` file which makes it easier to test (or send to someone else to test).

Eventually, I'd like to a GitHub workflow to build on PRs and upload the `.vsix` as an artifact to make it easier to test. Not directly related to this PR but should help for future troubleshooting!

File: src/storage.ts (hunk 10 above)
Comment (jsjoeio) [reply src/storage.ts:86]: Good question! So this method calls `fs.stat` and has a `catch` method which returns `false` basically saying the path/file doesn't exist. I think it's okay as is for now!

Comment (Kira-Pilot) [reply src/storage.ts:86]: Oh ya! Looks great.
